// Code generated by apidtogen; DO NOT EDIT.

package api

import "github.com/google/uuid"

type TestEmbedded struct {
	ID uuid.UUID `gorm:"primary_key" json:"id" mapstructure:"id" yaml:"id"`
}

type TestWidget struct {
	ID       uuid.UUID `gorm:"primary_key" json:"id" mapstructure:"id" yaml:"id"`
	WodgetID uuid.UUID `gorm:"type:uuid;" json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Name     string    `gorm:"type:text;" json:"name" mapstructure:"name" yaml:"name"`
	Category int       `gorm:"type:numeric(2);" json:"age" mapstructure:"age" yaml:"age"`
}

type TestWidgets []*TestWidget

type TestWodget struct {
	ID      uuid.UUID   `gorm:"primary_key" json:"id" mapstructure:"id" yaml:"id"`
	Widgets TestWidgets `gorm:"foreignkey:WodgetID" json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgets []TestWodget

type TestWadget struct {
	Ref      uuid.UUID   `gorm:"type:uuid;primaryKey" json:"ref" mapstructure:"ref" yaml:"ref"`
	Key      string      `gorm:"primary_key" json:"key" mapstructure:"key" yaml:"key"`
	DepField string      `gorm:"type:text;" json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	WodgetID uuid.UUID   `gorm:"type:uuid;" json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  TestWodgets `gorm:"foreignkey:WodgetID" json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestDeprecatedStruct struct {
	ID uuid.UUID `gorm:"primary_key" json:"id" mapstructure:"id" yaml:"id"`
}
