// Code generated by apimodelgen; DO NOT EDIT.

package api

import (
	"fmt"
	"github.com/google/uuid"
)

type PatchSlice[T any] struct {
	Replace *[]T `json:"replace,omitempty" mapstructure:"replace,omitempty" toml:"replace,omitempty" yaml:"replace,omitempty"`
	Patch   *[]T `json:"patch,omitempty" mapstructure:"patch,omitempty" toml:"patch,omitempty" yaml:"patch,omitempty"`
	Add     *[]T `json:"add,omitempty" mapstructure:"add,omitempty" toml:"add,omitempty" yaml:"add,omitempty"`
	Remove  *[]T `json:"remove,omitempty" mapstructure:"remove,omitempty" toml:"remove,omitempty" yaml:"remove,omitempty"`
}

func (ps *PatchSlice[T]) Validate() error {
	if ps == nil {
		return nil
	}
	count := 0
	if ps.Replace != nil {
		count++
	}
	if ps.Patch != nil {
		count++
	}
	if ps.Add != nil {
		count++
	}
	if ps.Remove != nil {
		count++
	}
	if count > 1 {
		return fmt.Errorf("PatchSlice: only one of Replace, Patch, Add, Remove may be non-nil")
	}
	return nil
}

type TestEmbedded struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedGeneric struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedGenericPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestWadget struct {
	Ref      uuid.UUID   `json:"ref" mapstructure:"ref" yaml:"ref"`
	Key      string      `json:"key" mapstructure:"key" yaml:"key"`
	DepField string      `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	WodgetID uuid.UUID   `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  TestWodgets `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestWadgetPatch struct {
	Ref      uuid.UUID                    `json:"ref" mapstructure:"ref" yaml:"ref"`
	Key      *string                      `json:"key" mapstructure:"key" yaml:"key"`
	DepField *string                      `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	WodgetID *uuid.UUID                   `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  *PatchSlice[TestWodgetPatch] `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestWidget struct {
	ID       uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WodgetID uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Name     string    `json:"name" mapstructure:"name" yaml:"name"`
	Category int       `json:"age" mapstructure:"age" yaml:"age"`
}

type TestWidgetGeneric struct {
	ID       uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WidgetID uuid.UUID `json:"widget_id" mapstructure:"widget_id" yaml:"widget_id"`
}

type TestWidgetGenericPatch struct {
	ID       *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WidgetID *uuid.UUID `json:"widget_id" mapstructure:"widget_id" yaml:"widget_id"`
}

type TestWidgetPatch struct {
	ID       *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WodgetID *uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Name     *string    `json:"name" mapstructure:"name" yaml:"name"`
	Category *int       `json:"age" mapstructure:"age" yaml:"age"`
}

type TestWidgets []*TestWidget

type TestWodget struct {
	ID      uuid.UUID   `json:"id" mapstructure:"id" yaml:"id"`
	Widgets TestWidgets `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgetPatch struct {
	ID      *uuid.UUID                    `json:"id" mapstructure:"id" yaml:"id"`
	Widgets *PatchSlice[*TestWidgetPatch] `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgets []TestWodget

func (dto TestEmbedded) ToPatch() TestEmbeddedPatch {
	return TestEmbeddedPatch{ID: &(dto.ID)}
}

func (dto TestEmbeddedGeneric) ToPatch() TestEmbeddedGenericPatch {
	return TestEmbeddedGenericPatch{ID: &(dto.ID)}
}

func (dto TestWadget) ToPatch() TestWadgetPatch {
	return TestWadgetPatch{
		DepField: &(dto.DepField),
		Key:      &(dto.Key),
		Ref:      dto.Ref,
		WodgetID: &(dto.WodgetID),
		Wodgets:  nil,
	}
}

func (dto TestWidget) ToPatch() TestWidgetPatch {
	return TestWidgetPatch{
		Category: &(dto.Category),
		ID:       &(dto.ID),
		Name:     &(dto.Name),
		WodgetID: &(dto.WodgetID),
	}
}

func (dto TestWidgetGeneric) ToPatch() TestWidgetGenericPatch {
	return TestWidgetGenericPatch{
		ID:       &(dto.ID),
		WidgetID: &(dto.WidgetID),
	}
}

func (dto TestWodget) ToPatch() TestWodgetPatch {
	return TestWodgetPatch{
		ID:      &(dto.ID),
		Widgets: nil,
	}
}
