// Code generated by apimodelgen; DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/google/uuid"
)

type PatchSlice[T any] struct {
	Replace *[]T `json:"replace,omitempty" mapstructure:"replace,omitempty" toml:"replace,omitempty" yaml:"replace,omitempty"`
	Patch   *[]T `json:"patch,omitempty" mapstructure:"patch,omitempty" toml:"patch,omitempty" yaml:"patch,omitempty"`
	Add     *[]T `json:"add,omitempty" mapstructure:"add,omitempty" toml:"add,omitempty" yaml:"add,omitempty"`
	Remove  *[]T `json:"remove,omitempty" mapstructure:"remove,omitempty" toml:"remove,omitempty" yaml:"remove,omitempty"`
}

func (ps *PatchSlice[T]) Validate() error {
	if ps == nil {
		return nil
	}
	count := 0
	if ps.Replace != nil {
		count++
	}
	if ps.Patch != nil {
		count++
	}
	if ps.Add != nil {
		count++
	}
	if ps.Remove != nil {
		count++
	}
	if count > 1 {
		return fmt.Errorf("PatchSlice: only one of Replace, Patch, Add, Remove may be non-nil")
	}
	return nil
}

type TestDeprecatedStruct struct{}

type TestEmbedded struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedGeneric struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedGenericPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestWadget struct {
	DepField string      `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	Key      string      `json:"key" mapstructure:"key" yaml:"key"`
	Ref      uuid.UUID   `json:"ref" mapstructure:"ref" yaml:"ref"`
	WodgetID uuid.UUID   `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  TestWodgets `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestWadgetPatch struct {
	DepField *string                      `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	Key      *string                      `json:"key" mapstructure:"key" yaml:"key"`
	Ref      uuid.UUID                    `json:"ref" mapstructure:"ref" yaml:"ref"`
	WodgetID *uuid.UUID                   `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  *PatchSlice[TestWodgetPatch] `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestWidget struct {
	Category int       `json:"age" mapstructure:"age" yaml:"age"`
	Name     string    `json:"name" mapstructure:"name" yaml:"name"`
	WodgetID uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
}

type TestWidgetGeneric struct {
	TestEmbeddedGeneric `json:",inline" mapstructure:",squash" yaml:",inline"`
	WidgetID            uuid.UUID `json:"widget_id" mapstructure:"widget_id" yaml:"widget_id"`
}

type TestWidgetGenericPatch struct {
	TestEmbeddedGeneric *TestEmbeddedGenericPatch `json:",inline" mapstructure:",squash" yaml:",inline"`
	WidgetID            *uuid.UUID                `json:"widget_id" mapstructure:"widget_id" yaml:"widget_id"`
}

type TestWidgetPatch struct {
	Category *int       `json:"age" mapstructure:"age" yaml:"age"`
	Name     *string    `json:"name" mapstructure:"name" yaml:"name"`
	WodgetID *uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
}

type TestWidgets []*TestWidget

type TestWodget struct {
	Widgets TestWidgets `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgetPatch struct {
	Widgets *PatchSlice[*TestWidgetPatch] `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgets []TestWodget

func (dto TestEmbedded) ToPatch() TestEmbeddedPatch {
	return TestEmbeddedPatch{ID: &(dto.ID)}
}

func (dto TestEmbeddedGeneric) ToPatch() TestEmbeddedGenericPatch {
	return TestEmbeddedGenericPatch{ID: &(dto.ID)}
}

func (dto TestWadget) ToPatch() TestWadgetPatch {
	return TestWadgetPatch{
		DepField: &(dto.DepField),
		Key:      &(dto.Key),
		Ref:      dto.Ref,
		WodgetID: &(dto.WodgetID),
		Wodgets:  nil,
	}
}

func (dto TestWidget) ToPatch() TestWidgetPatch {
	return TestWidgetPatch{
		Category: &(dto.Category),
		Name:     &(dto.Name),
		WodgetID: &(dto.WodgetID),
	}
}

func (dto TestWidgetGeneric) ToPatch() TestWidgetGenericPatch {
	return TestWidgetGenericPatch{
		TestEmbeddedGeneric: (func() *TestEmbeddedGenericPatch {
			tmp := dto.TestEmbeddedGeneric.ToPatch()
			return &tmp
		}()),
		WidgetID: &(dto.WidgetID),
	}
}

func (dto TestWodget) ToPatch() TestWodgetPatch {
	return TestWodgetPatch{Widgets: nil}
}
