// Code generated by apimodelgen; DO NOT EDIT.

package api

import (
	"fmt"
	"github.com/google/uuid"
)

type PatchSlice[T any] struct {
	Replace *[]T `json:"replace,omitempty" mapstructure:"replace,omitempty" toml:"replace,omitempty" yaml:"replace,omitempty"`
	Patch   *[]T `json:"patch,omitempty" mapstructure:"patch,omitempty" toml:"patch,omitempty" yaml:"patch,omitempty"`
	Add     *[]T `json:"add,omitempty" mapstructure:"add,omitempty" toml:"add,omitempty" yaml:"add,omitempty"`
	Remove  *[]T `json:"remove,omitempty" mapstructure:"remove,omitempty" toml:"remove,omitempty" yaml:"remove,omitempty"`
}

func (ps *PatchSlice[T]) Validate() error {
	if ps == nil {
		return nil
	}
	count := 0
	if ps.Replace != nil {
		count++
	}
	if ps.Patch != nil {
		count++
	}
	if ps.Add != nil {
		count++
	}
	if ps.Remove != nil {
		count++
	}
	if count > 1 {
		return fmt.Errorf("PatchSlice: only one of Replace, Patch, Add, Remove may be non-nil")
	}
	return nil
}

type TestDeprecatedStructOut struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestDeprecatedStructOutPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedGenericOut struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedGenericOutPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedOut struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestEmbeddedOutPatch struct {
	ID *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestWadgetOut struct {
	DepField string         `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	Key      string         `json:"key" mapstructure:"key" yaml:"key"`
	Ref      uuid.UUID      `json:"ref" mapstructure:"ref" yaml:"ref"`
	WodgetID uuid.UUID      `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  TestWodgetsOut `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestWadgetOutPatch struct {
	DepField *string                         `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	Key      *string                         `json:"key" mapstructure:"key" yaml:"key"`
	Ref      uuid.UUID                       `json:"ref" mapstructure:"ref" yaml:"ref"`
	WodgetID *uuid.UUID                      `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  *PatchSlice[TestWodgetOutPatch] `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestWidgetGenericOut struct {
	ID       uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WidgetID uuid.UUID `json:"widget_id" mapstructure:"widget_id" yaml:"widget_id"`
}

type TestWidgetGenericOutPatch struct {
	ID       *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WidgetID *uuid.UUID `json:"widget_id" mapstructure:"widget_id" yaml:"widget_id"`
}

type TestWidgetOut struct {
	Category int       `json:"age" mapstructure:"age" yaml:"age"`
	ID       uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	Name     string    `json:"name" mapstructure:"name" yaml:"name"`
	WodgetID uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
}

type TestWidgetOutPatch struct {
	Category *int       `json:"age" mapstructure:"age" yaml:"age"`
	ID       *uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	Name     *string    `json:"name" mapstructure:"name" yaml:"name"`
	WodgetID *uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
}

type TestWidgetsOut []*TestWidgetOut

type TestWodgetOut struct {
	ID      uuid.UUID      `json:"id" mapstructure:"id" yaml:"id"`
	Widgets TestWidgetsOut `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgetOutPatch struct {
	ID      *uuid.UUID                       `json:"id" mapstructure:"id" yaml:"id"`
	Widgets *PatchSlice[*TestWidgetOutPatch] `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgetsOut []TestWodgetOut

func (dto TestDeprecatedStructOut) ToPatch() TestDeprecatedStructOutPatch {
	return TestDeprecatedStructOutPatch{ID: &(dto.ID)}
}

func (dto TestEmbeddedGenericOut) ToPatch() TestEmbeddedGenericOutPatch {
	return TestEmbeddedGenericOutPatch{ID: &(dto.ID)}
}

func (dto TestEmbeddedOut) ToPatch() TestEmbeddedOutPatch {
	return TestEmbeddedOutPatch{ID: &(dto.ID)}
}

func (dto TestWadgetOut) ToPatch() TestWadgetOutPatch {
	return TestWadgetOutPatch{
		DepField: &(dto.DepField),
		Key:      &(dto.Key),
		Ref:      dto.Ref,
		WodgetID: &(dto.WodgetID),
		Wodgets:  nil,
	}
}

func (dto TestWidgetGenericOut) ToPatch() TestWidgetGenericOutPatch {
	return TestWidgetGenericOutPatch{
		ID:       &(dto.ID),
		WidgetID: &(dto.WidgetID),
	}
}

func (dto TestWidgetOut) ToPatch() TestWidgetOutPatch {
	return TestWidgetOutPatch{
		Category: &(dto.Category),
		ID:       &(dto.ID),
		Name:     &(dto.Name),
		WodgetID: &(dto.WodgetID),
	}
}

func (dto TestWodgetOut) ToPatch() TestWodgetOutPatch {
	return TestWodgetOutPatch{
		ID:      &(dto.ID),
		Widgets: nil,
	}
}
