// Code generated by apidtogen; DO NOT EDIT.

package api

import "github.com/google/uuid"

type TestEmbeddedOut struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestWidgetOut struct {
	ID       uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WodgetID uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Name     string    `json:"name" mapstructure:"name" yaml:"name"`
	Category int       `json:"age" mapstructure:"age" yaml:"age"`
}

type TestWidgetsOut []*TestWidgetOut

type TestWodgetOut struct {
	ID      uuid.UUID      `json:"id" mapstructure:"id" yaml:"id"`
	Widgets TestWidgetsOut `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgetsOut []TestWodgetOut

type TestWadgetOut struct {
	Ref      uuid.UUID      `json:"ref" mapstructure:"ref" yaml:"ref"`
	Key      string         `json:"key" mapstructure:"key" yaml:"key"`
	DepField string         `json:"dep_field" mapstructure:"dep_field" yaml:"dep_field"`
	WodgetID uuid.UUID      `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  TestWodgetsOut `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}

type TestDeprecatedStructOut struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}
