// Code generated by apidtogen; DO NOT EDIT.

package api

import "github.com/google/uuid"

type TestEmbedded struct {
	ID uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
}

type TestWidget struct {
	ID       uuid.UUID `json:"id" mapstructure:"id" yaml:"id"`
	WodgetID uuid.UUID `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Name     string    `json:"name" mapstructure:"name" yaml:"name"`
	Category int       `json:"age" mapstructure:"age" yaml:"age"`
}

type TestWidgets []*TestWidget

type TestWodget struct {
	ID      uuid.UUID   `json:"id" mapstructure:"id" yaml:"id"`
	Widgets TestWidgets `json:"widgets" mapstructure:"widgets" yaml:"widgets"`
}

type TestWodgets []TestWodget

type TestWadget struct {
	Ref      uuid.UUID   `json:"ref" mapstructure:"ref" yaml:"ref"`
	Key      string      `json:"key" mapstructure:"key" yaml:"key"`
	WodgetID uuid.UUID   `json:"wodget_id" mapstructure:"wodget_id" yaml:"wodget_id"`
	Wodgets  TestWodgets `json:"wodgets" mapstructure:"wodgets" yaml:"wodgets"`
}
